Feature/car resource
NFKData/CarApp pull request #5
Opened 2019-05-21 14:55 UTC by NFKData

2019-05-21 14:55 UTC, NFKData commented
![](https://github.trello.services/images/mini-trello-icon.png) [Car Resource, API REST implementation (JAX-RS)](https://trello.com/c/cQ3e5WtC/11-car-resource-api-rest-implementation-jax-rs)

2019-05-22 09:23 UTC, javieraviles commented on CarAppBackend/src/main/java/backend/exception/CarNotFoundException.java
> +public class CarNotFoundException extends Exception {
javadocs missing here

2019-05-22 09:24 UTC, javieraviles commented on CarAppBackend/src/main/java/backend/resource/CarResource.java
> +public class CarResource {
as it's been done for the service, i would create an interface with javadocs and other future annotations

2019-05-22 09:25 UTC, javieraviles commented on CarAppBackend/src/main/java/backend/resource/CarResource.java
> +	@Produces(MediaType.APPLICATION_JSON)
extract consumes/produces at class level

2019-05-22 09:28 UTC, javieraviles requested changes
some small fixes required

2019-05-22 10:28 UTC, javieraviles approved these changes

2019-05-22 10:29 UTC, merged